### PR TITLE
fix: update season duration values

### PR DESCRIPTION
**Pull request by mmsheeks**
see issue #67 for details

### CODE REVIEW

**Review by BenjaminCelis — CHANGES_REQUESTED** [review]
What I've found a MC day is 24000 ticks, so I think the values should be:
Spring: 360000
Summer: 720000
Fall: 120000
Winter: 240000

Idk what the values currently are representing?

**Comment by mmsheeks** [comment]
The values I've updated them to are based on real world time calculations, not in-game day. Generated using [this calculator](https://mapmaking.fr/tick/). Should equate to the correct number of ticks for the real-time day lengths, player sleep cycles not withstanding.

**Comment by BenjaminCelis** [comment]
ahnn makes sense, Let me double calc and I'll accept if they match

**Review by BenjaminCelis — APPROVED** [review]
Yup, that checks out to RL days in ticks!

**Pull request merged**
